import = ["~/.config/alacritty/themes/synthwave_84.toml"]
shell = "/bin/zsh"

[window]
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"
decorations_theme_variant = "dark"

[window.padding]
x = 10
y = 10


[font]
size = 15
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


[keyboard]
bindings = [
  { key = "ArrowRight", mods = "Option", action = "SelectNextTab" },
  { key = "ArrowLeft", mods = "Option", action = "SelectPreviousTab" },
]
