"$schema" = 'https://starship.rs/config-schema.json'


add_newline = false
format = "$directory$gi_branch$git_commit$git_state$git_metrics$git_status$python$kubernetes$line_break$character"

[directory]
fish_style_pwd_dir_length = 2


[kubernetes]
disabled = false
format = 'on [⎈ $namespace \($context\)](dimmed green) '
detect_folders = ["k8s", "manifests", "manifest"]


[helm]
disabled = true
detect_files = ["helmfile.yaml", "helmfile.yml", "Chart.yaml", "Chart.yml"]
